#SUBEDI RABIN M25W0465
spring.application.name=moviehub-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/moviehub
spring.datasource.username=moviehub_user
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=9292
